import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const palettes = {
  light: {
    name: "macOS Golden Gate — Light",
    type: "light",
    canvas: "#F2F2F7",
    editor: "#FFFFFF",
    chrome: "#F2F2F7E8",
    chromeSolid: "#F2F2F7",
    panel: "#F7F7FA",
    elevated: "#FFFFFFF2",
    input: "#FFFFFFB8",
    text: "#1D1D1F",
    editorText: "#242426",
    secondary: "#5C5C61",
    muted: "#737378",
    disabled: "#A1A1A6",
    border: "#0000001F",
    borderStrong: "#00000033",
    shadow: "#0000002B",
    overlay: "#0000000A",
    overlayStrong: "#00000014",
    selection: "#007AFF26",
    selectionStrong: "#007AFF3D",
    accent: "#007AFF",
    accentText: "#0066CC",
    accentHover: "#006EDB",
    accentWash: "#007AFF1F",
    accentForeground: "#FFFFFF",
    primary: "#006EDB",
    primaryHover: "#005CBD",
    primaryForeground: "#FFFFFF",
    blue: "#0066CC",
    blueBright: "#007AFF",
    blueWash: "#007AFF1F",
    blueForeground: "#FFFFFF",
    green: "#1F7A34",
    greenBright: "#34C759",
    greenWash: "#34C75924",
    red: "#D70015",
    redBright: "#D70015",
    redWash: "#FF3B3020",
    redForeground: "#FFFFFF",
    orange: "#A64B00",
    orangeBright: "#FF9500",
    orangeWash: "#FF950026",
    yellow: "#755B00",
    yellowBright: "#FFCC00",
    yellowWash: "#FFCC002B",
    cyan: "#007C91",
    cyanBright: "#32ADE6",
    purple: "#7D3C98",
    purpleBright: "#AF52DE",
    magenta: "#AD1457",
    gitIgnored: "#8A8A8F",
    white: "#FFFFFF",
    black: "#000000"
  },
  dark: {
    name: "macOS Golden Gate — Dark",
    type: "dark",
    canvas: "#0D0D0F",
    editor: "#111113",
    chrome: "#1C1C1EE6",
    chromeSolid: "#242426",
    panel: "#18181B",
    elevated: "#2C2C2EF2",
    input: "#00000066",
    text: "#F5F5F7",
    editorText: "#EDEDF0",
    secondary: "#B8B8BD",
    muted: "#8E8E93",
    disabled: "#5C5C61",
    border: "#FFFFFF1F",
    borderStrong: "#FFFFFF38",
    shadow: "#00000066",
    overlay: "#FFFFFF0D",
    overlayStrong: "#FFFFFF1A",
    selection: "#0A84FF33",
    selectionStrong: "#0A84FF4D",
    accent: "#0A84FF",
    accentText: "#409CFF",
    accentHover: "#409CFF",
    accentWash: "#0A84FF2E",
    accentForeground: "#001426",
    primary: "#0A84FF",
    primaryHover: "#409CFF",
    primaryForeground: "#001426",
    blue: "#409CFF",
    blueBright: "#0A84FF",
    blueWash: "#0A84FF2E",
    blueForeground: "#001426",
    green: "#63D17B",
    greenBright: "#30D158",
    greenWash: "#30D1582B",
    red: "#FF6961",
    redBright: "#FF453A",
    redWash: "#FF453A2B",
    redForeground: "#1C090A",
    orange: "#FFB340",
    orangeBright: "#FF9F0A",
    orangeWash: "#FF9F0A2B",
    yellow: "#FFE066",
    yellowBright: "#FFD60A",
    yellowWash: "#FFD60A2B",
    cyan: "#64D2FF",
    cyanBright: "#64D2FF",
    purple: "#D57AFF",
    purpleBright: "#BF5AF2",
    magenta: "#FF6482",
    gitIgnored: "#77777C",
    white: "#FFFFFF",
    black: "#000000"
  }
};

function makeColors(p) {
  const transparent = "#00000000";
  return {
    foreground: p.text,
    disabledForeground: p.disabled,
    errorForeground: p.red,
    descriptionForeground: p.secondary,
    "icon.foreground": p.secondary,
    focusBorder: p.accent,
    "window.activeBorder": p.borderStrong,
    "window.inactiveBorder": p.border,

    "textBlockQuote.background": p.overlay,
    "textBlockQuote.border": p.accent,
    "textCodeBlock.background": p.overlay,
    "textLink.foreground": p.blue,
    "textLink.activeForeground": p.blueBright,
    "textPreformat.background": p.overlay,
    "textPreformat.foreground": p.accentText,
    "textSeparator.foreground": p.border,

    "button.background": p.primary,
    "button.foreground": p.primaryForeground,
    "button.hoverBackground": p.primaryHover,
    "button.border": p.borderStrong,
    "button.separator": p.borderStrong,
    "button.secondaryBackground": p.overlay,
    "button.secondaryForeground": p.text,
    "button.secondaryHoverBackground": p.overlayStrong,
    "button.secondaryBorder": p.border,

    "checkbox.background": p.input,
    "checkbox.border": p.borderStrong,
    "checkbox.foreground": p.text,
    "checkbox.selectBackground": p.accentWash,
    "checkbox.selectBorder": p.accent,
    "dropdown.background": p.elevated,
    "dropdown.border": p.border,
    "dropdown.foreground": p.text,
    "dropdown.listBackground": p.elevated,
    "input.background": p.input,
    "input.border": p.border,
    "input.foreground": p.text,
    "input.placeholderForeground": p.muted,
    "inputOption.activeBackground": p.accentWash,
    "inputOption.activeBorder": p.accent,
    "inputOption.activeForeground": p.text,
    "inputOption.hoverBackground": p.overlay,
    "inputValidation.infoBackground": p.blueWash,
    "inputValidation.infoBorder": p.blue,
    "inputValidation.infoForeground": p.text,
    "inputValidation.warningBackground": p.yellowWash,
    "inputValidation.warningBorder": p.yellow,
    "inputValidation.warningForeground": p.text,
    "inputValidation.errorBackground": p.redWash,
    "inputValidation.errorBorder": p.red,
    "inputValidation.errorForeground": p.text,

    "scrollbar.background": transparent,
    "scrollbar.shadow": transparent,
    "scrollbarSlider.background": `${p.muted}52`,
    "scrollbarSlider.hoverBackground": `${p.muted}75`,
    "scrollbarSlider.activeBackground": `${p.secondary}8A`,
    "widget.shadow": p.shadow,
    "widget.border": p.border,
    "sash.hoverBorder": p.accent,
    "badge.background": p.primary,
    "badge.foreground": p.primaryForeground,
    "progressBar.background": p.accent,

    "list.activeSelectionBackground": p.selectionStrong,
    "list.activeSelectionForeground": p.text,
    "list.activeSelectionIconForeground": p.accentText,
    "list.inactiveSelectionBackground": p.selection,
    "list.inactiveSelectionForeground": p.text,
    "list.inactiveSelectionIconForeground": p.secondary,
    "list.hoverBackground": p.overlay,
    "list.hoverForeground": p.text,
    "list.dropBackground": p.accentWash,
    "list.focusBackground": p.selectionStrong,
    "list.focusForeground": p.text,
    "list.focusOutline": p.accent,
    "list.focusAndSelectionOutline": p.accent,
    "list.highlightForeground": p.accentText,
    "list.deemphasizedForeground": p.muted,
    "list.invalidItemForeground": p.disabled,
    "list.errorForeground": p.red,
    "list.warningForeground": p.orange,
    "listFilterWidget.background": p.elevated,
    "listFilterWidget.outline": p.border,
    "listFilterWidget.noMatchesOutline": p.red,
    "listFilterWidget.shadow": transparent,
    "tree.indentGuidesStroke": p.border,
    "tree.inactiveIndentGuidesStroke": p.border,
    "tree.tableColumnsBorder": p.border,
    "tree.tableOddRowsBackground": p.overlay,

    "activityBar.background": p.chrome,
    "activityBar.foreground": p.text,
    "activityBar.inactiveForeground": p.muted,
    "activityBar.border": p.border,
    "activityBar.activeBorder": p.accent,
    "activityBar.activeBackground": p.accentWash,
    "activityBar.activeFocusBorder": p.accent,
    "activityBar.dropBorder": p.accent,
    "activityBarBadge.background": p.primary,
    "activityBarBadge.foreground": p.primaryForeground,
    "activityBarTop.foreground": p.text,
    "activityBarTop.inactiveForeground": p.muted,
    "activityBarTop.activeBorder": p.accent,
    "activityBarTop.activeBackground": p.accentWash,
    "activityBarTop.dropBorder": p.accent,
    "sideBar.background": p.chrome,
    "sideBar.foreground": p.text,
    "sideBar.border": p.border,
    "sideBar.dropBackground": p.accentWash,
    "sideBarTitle.background": transparent,
    "sideBarTitle.foreground": p.text,
    "sideBarTitle.border": p.border,
    "sideBarSectionHeader.background": p.overlay,
    "sideBarSectionHeader.foreground": p.text,
    "sideBarSectionHeader.border": p.border,
    "sideBarActivityBarTop.border": p.border,
    "sideBarStickyScroll.background": p.chromeSolid,
    "sideBarStickyScroll.border": p.border,
    "sideBarStickyScroll.shadow": transparent,
    "activityWarningBadge.background": p.yellowBright,
    "activityWarningBadge.foreground": p.black,
    "activityErrorBadge.background": p.redBright,
    "activityErrorBadge.foreground": p.redForeground,

    "titleBar.activeBackground": p.chrome,
    "titleBar.activeForeground": p.text,
    "titleBar.inactiveBackground": p.chrome,
    "titleBar.inactiveForeground": p.muted,
    "titleBar.border": p.border,
    "menubar.selectionBackground": p.overlayStrong,
    "menubar.selectionForeground": p.text,
    "menubar.selectionBorder": transparent,
    "menu.background": p.elevated,
    "menu.foreground": p.text,
    "menu.selectionBackground": p.selectionStrong,
    "menu.selectionForeground": p.text,
    "menu.selectionBorder": transparent,
    "menu.separatorBackground": p.border,
    "menu.border": p.border,
    "commandCenter.foreground": p.secondary,
    "commandCenter.activeForeground": p.text,
    "commandCenter.inactiveForeground": p.muted,
    "commandCenter.background": p.input,
    "commandCenter.activeBackground": p.overlay,
    "commandCenter.border": p.border,
    "commandCenter.activeBorder": p.borderStrong,
    "commandCenter.inactiveBorder": p.border,
    "commandCenter.debuggingBackground": p.blueWash,

    "editor.background": p.editor,
    "editor.foreground": p.editorText,
    "editorGroup.emptyBackground": p.canvas,
    "editorGroup.border": p.border,
    "editorGroup.dropBackground": p.accentWash,
    "editorPane.background": p.editor,
    "editorLineNumber.foreground": p.muted,
    "editorLineNumber.activeForeground": p.text,
    "editorLineNumber.dimmedForeground": p.disabled,
    "editorCursor.foreground": p.accentText,
    "editorCursor.background": p.editor,
    "editor.multiCursorPrimary.foreground": p.accentText,
    "editor.multiCursorSecondary.foreground": p.blue,
    "editor.selectionBackground": p.selectionStrong,
    "editor.inactiveSelectionBackground": p.selection,
    "editor.selectionHighlightBackground": p.accentWash,
    "editor.wordHighlightBackground": p.blueWash,
    "editor.wordHighlightStrongBackground": p.selection,
    "editor.wordHighlightTextBackground": p.overlayStrong,
    "editor.findMatchBackground": p.yellowWash,
    "editor.findMatchForeground": p.text,
    "editor.findMatchHighlightBackground": `${p.yellowBright}24`,
    "editor.findRangeHighlightBackground": p.overlay,
    "editor.hoverHighlightBackground": p.overlayStrong,
    "editor.lineHighlightBackground": p.overlay,
    "editor.lineHighlightBorder": transparent,
    "editor.rangeHighlightBackground": p.overlay,
    "editor.symbolHighlightBackground": p.accentWash,
    "editorLink.activeForeground": p.blueBright,
    "editorWhitespace.foreground": `${p.muted}4D`,
    "editorIndentGuide.background1": p.border,
    "editorIndentGuide.activeBackground1": p.accent,
    "editorRuler.foreground": p.border,
    "editorCodeLens.foreground": p.muted,
    "editorLightBulb.foreground": p.yellow,
    "editorLightBulbAutoFix.foreground": p.blue,
    "editorBracketMatch.background": p.accentWash,
    "editorBracketMatch.border": p.accent,
    "editorBracketHighlight.foreground1": p.blue,
    "editorBracketHighlight.foreground2": p.purple,
    "editorBracketHighlight.foreground3": p.orange,
    "editorBracketHighlight.foreground4": p.cyan,
    "editorBracketHighlight.foreground5": p.green,
    "editorBracketHighlight.foreground6": p.magenta,
    "editorBracketHighlight.unexpectedBracket.foreground": p.red,
    "editor.foldBackground": p.accentWash,
    "editor.snippetTabstopHighlightBackground": p.blueWash,
    "editor.snippetTabstopHighlightBorder": p.blue,
    "editor.snippetFinalTabstopHighlightBackground": p.accentWash,
    "editor.snippetFinalTabstopHighlightBorder": p.accent,
    "editorUnicodeHighlight.border": p.orange,
    "editorUnicodeHighlight.background": p.orangeWash,
    "editorInfo.foreground": p.blue,
    "editorWarning.foreground": p.orange,
    "editorError.foreground": p.red,
    "editorHint.foreground": p.green,
    "editorUnnecessaryCode.opacity": "#00000099",
    "editorGhostText.foreground": p.muted,
    "editorGhostText.background": transparent,
    "editorStickyScroll.background": p.editor,
    "editorStickyScrollHover.background": p.overlayStrong,
    "editorStickyScroll.border": p.border,
    "editorStickyScroll.shadow": transparent,
    "editorStickyScrollGutter.background": p.editor,

    "editorWidget.background": p.elevated,
    "editorWidget.foreground": p.text,
    "editorWidget.border": p.border,
    "editorWidget.resizeBorder": p.accent,
    "editorSuggestWidget.background": p.elevated,
    "editorSuggestWidget.border": p.border,
    "editorSuggestWidget.foreground": p.text,
    "editorSuggestWidget.highlightForeground": p.accentText,
    "editorSuggestWidget.focusHighlightForeground": p.accentText,
    "editorSuggestWidget.selectedBackground": p.selectionStrong,
    "editorSuggestWidget.selectedForeground": p.text,
    "editorSuggestWidget.selectedIconForeground": p.accentText,
    "editorSuggestWidgetStatus.foreground": p.secondary,
    "editorHoverWidget.background": p.elevated,
    "editorHoverWidget.foreground": p.text,
    "editorHoverWidget.border": p.border,
    "editorHoverWidget.highlightForeground": p.accentText,
    "editorHoverWidget.statusBarBackground": p.overlay,
    "editorMarkerNavigation.background": p.elevated,
    "editorMarkerNavigationError.background": p.red,
    "editorMarkerNavigationWarning.background": p.orange,
    "editorMarkerNavigationInfo.background": p.blue,
    "editorMarkerNavigationError.headerBackground": p.redWash,
    "editorMarkerNavigationWarning.headerBackground": p.orangeWash,
    "editorMarkerNavigationInfo.headerBackground": p.blueWash,

    "peekView.border": p.accent,
    "peekViewEditor.background": p.editor,
    "peekViewEditor.matchHighlightBackground": p.yellowWash,
    "peekViewEditorGutter.background": p.editor,
    "peekViewResult.background": p.panel,
    "peekViewResult.fileForeground": p.text,
    "peekViewResult.lineForeground": p.secondary,
    "peekViewResult.matchHighlightBackground": p.yellowWash,
    "peekViewResult.selectionBackground": p.selectionStrong,
    "peekViewResult.selectionForeground": p.text,
    "peekViewTitle.background": p.chromeSolid,
    "peekViewTitleDescription.foreground": p.secondary,
    "peekViewTitleLabel.foreground": p.text,

    "editorGutter.background": p.editor,
    "editorGutter.addedBackground": p.green,
    "editorGutter.modifiedBackground": p.blue,
    "editorGutter.deletedBackground": p.red,
    "editorGutter.commentRangeForeground": p.muted,
    "editorGutter.commentGlyphForeground": p.blue,
    "editorGutter.commentUnresolvedGlyphForeground": p.orange,
    "editorOverviewRuler.border": p.border,
    "editorOverviewRuler.background": transparent,
    "editorOverviewRuler.findMatchForeground": p.yellow,
    "editorOverviewRuler.rangeHighlightForeground": p.accent,
    "editorOverviewRuler.selectionHighlightForeground": p.accent,
    "editorOverviewRuler.wordHighlightForeground": p.blue,
    "editorOverviewRuler.wordHighlightStrongForeground": p.purple,
    "editorOverviewRuler.modifiedForeground": p.blue,
    "editorOverviewRuler.addedForeground": p.green,
    "editorOverviewRuler.deletedForeground": p.red,
    "editorOverviewRuler.errorForeground": p.red,
    "editorOverviewRuler.warningForeground": p.orange,
    "editorOverviewRuler.infoForeground": p.blue,
    "editorOverviewRuler.bracketMatchForeground": p.accent,

    "diffEditor.insertedLineBackground": p.greenWash,
    "diffEditor.insertedTextBackground": `${p.greenBright}38`,
    "diffEditor.removedLineBackground": p.redWash,
    "diffEditor.removedTextBackground": `${p.redBright}38`,
    "diffEditor.diagonalFill": p.border,
    "diffEditor.border": p.border,
    "diffEditor.unchangedRegionBackground": p.panel,
    "diffEditor.unchangedRegionForeground": p.secondary,
    "diffEditor.unchangedRegionShadow": transparent,
    "diffEditor.unchangedCodeBackground": p.overlay,
    "diffEditor.move.border": p.purple,
    "diffEditor.moveActive.border": p.accent,
    "multiDiffEditor.headerBackground": p.chrome,
    "multiDiffEditor.background": p.canvas,
    "multiDiffEditor.border": p.border,

    "minimap.background": p.editor,
    "minimap.findMatchHighlight": p.yellow,
    "minimap.selectionHighlight": p.accent,
    "minimap.errorHighlight": p.red,
    "minimap.warningHighlight": p.orange,
    "minimap.selectionOccurrenceHighlight": p.accentText,
    "minimap.foregroundOpacity": "#000000B3",
    "minimapSlider.background": `${p.muted}42`,
    "minimapSlider.hoverBackground": `${p.muted}66`,
    "minimapSlider.activeBackground": `${p.secondary}7A`,
    "problemsErrorIcon.foreground": p.red,
    "problemsWarningIcon.foreground": p.orange,
    "problemsInfoIcon.foreground": p.blue,

    "panel.background": p.panel,
    "panel.border": p.border,
    "panel.dropBorder": p.accent,
    "panelTitle.activeBorder": p.accent,
    "panelTitle.activeForeground": p.text,
    "panelTitle.inactiveForeground": p.secondary,
    "panelTitle.border": p.border,
    "panelInput.border": p.border,
    "panelSection.border": p.border,
    "panelSection.dropBackground": p.accentWash,
    "panelSectionHeader.background": p.overlay,
    "panelSectionHeader.foreground": p.text,
    "panelSectionHeader.border": p.border,
    "panelStickyScroll.background": p.chromeSolid,
    "panelStickyScroll.border": p.border,
    "panelStickyScroll.shadow": transparent,
    "auxiliaryBar.background": p.chrome,
    "auxiliaryBar.foreground": p.text,
    "auxiliaryBar.border": p.border,
    "auxiliaryBarTitle.foreground": p.text,

    "statusBar.background": p.chrome,
    "statusBar.foreground": p.secondary,
    "statusBar.border": p.border,
    "statusBar.focusBorder": p.accent,
    "statusBar.noFolderBackground": p.chrome,
    "statusBar.noFolderForeground": p.secondary,
    "statusBar.debuggingBackground": p.blue,
    "statusBar.debuggingForeground": p.blueForeground,
    "statusBarItem.activeBackground": p.overlayStrong,
    "statusBarItem.hoverBackground": p.overlayStrong,
    "statusBarItem.hoverForeground": p.text,
    "statusBarItem.focusBorder": p.accent,
    "statusBarItem.prominentBackground": p.accentWash,
    "statusBarItem.prominentForeground": p.text,
    "statusBarItem.prominentHoverBackground": p.selectionStrong,
    "statusBarItem.prominentHoverForeground": p.text,
    "statusBarItem.remoteBackground": p.primary,
    "statusBarItem.remoteForeground": p.primaryForeground,
    "statusBarItem.errorBackground": p.red,
    "statusBarItem.errorForeground": p.redForeground,
    "statusBarItem.warningBackground": p.yellowBright,
    "statusBarItem.warningForeground": p.black,
    "statusBarItem.offlineBackground": p.overlay,
    "statusBarItem.offlineForeground": p.secondary,
    "statusBarItem.offlineHoverBackground": p.overlayStrong,
    "statusBarItem.offlineHoverForeground": p.text,

    "editorGroupHeader.tabsBackground": p.chrome,
    "editorGroupHeader.tabsBorder": p.border,
    "editorGroupHeader.noTabsBackground": p.chrome,
    "editorGroupHeader.border": p.border,
    "tab.activeBackground": p.type === "dark" ? `${p.text}2E` : `${p.text}1A`,
    "tab.activeForeground": p.text,
    "tab.activeBorder": transparent,
    "tab.activeBorderTop": transparent,
    "tab.selectedBorderTop": transparent,
    "tab.inactiveBackground": p.type === "dark" ? `${p.text}0D` : `${p.text}0A`,
    "tab.inactiveForeground": p.secondary,
    "tab.hoverBackground": p.type === "dark" ? `${p.text}14` : `${p.text}0F`,
    "tab.hoverForeground": p.text,
    "tab.hoverBorder": transparent,
    "tab.unfocusedActiveBackground": p.type === "dark" ? `${p.text}2E` : `${p.text}1A`,
    "tab.unfocusedActiveForeground": p.secondary,
    "tab.unfocusedActiveBorder": transparent,
    "tab.unfocusedActiveBorderTop": transparent,
    "tab.unfocusedInactiveBackground": p.type === "dark" ? `${p.text}0D` : `${p.text}0A`,
    "tab.unfocusedInactiveForeground": p.muted,
    "tab.unfocusedHoverBackground": p.type === "dark" ? `${p.text}14` : `${p.text}0F`,
    "tab.unfocusedHoverForeground": p.secondary,
    "tab.border": transparent,
    "tab.lastPinnedBorder": p.borderStrong,
    "tab.dragAndDropBorder": p.accent,

    "breadcrumb.background": p.editor,
    "breadcrumb.foreground": p.secondary,
    "breadcrumb.focusForeground": p.text,
    "breadcrumb.activeSelectionForeground": p.accentText,
    "breadcrumbPicker.background": p.elevated,

    "notifications.background": p.elevated,
    "notifications.foreground": p.text,
    "notifications.border": p.border,
    "notificationsErrorIcon.foreground": p.red,
    "notificationsWarningIcon.foreground": p.orange,
    "notificationsInfoIcon.foreground": p.blue,
    "notificationCenter.border": p.border,
    "notificationCenterHeader.background": p.chromeSolid,
    "notificationCenterHeader.foreground": p.text,
    "notificationToast.border": p.border,
    "notificationLink.foreground": p.blue,
    "extensionButton.prominentBackground": p.primary,
    "extensionButton.prominentForeground": p.primaryForeground,
    "extensionButton.prominentHoverBackground": p.primaryHover,
    "extensionIcon.starForeground": p.yellow,
    "extensionIcon.verifiedForeground": p.blue,
    "extensionIcon.preReleaseForeground": p.purple,
    "extensionIcon.sponsorForeground": p.magenta,

    "pickerGroup.border": p.border,
    "pickerGroup.foreground": p.accentText,
    "quickInput.background": p.elevated,
    "quickInput.foreground": p.text,
    "quickInputTitle.background": p.chromeSolid,
    "quickInputList.focusBackground": p.selectionStrong,
    "quickInputList.focusForeground": p.text,
    "quickInputList.focusIconForeground": p.accentText,
    "quickInputList.focusHighlightForeground": p.accentText,
    "quickInputList.hoverBackground": p.overlay,
    "quickInputList.hoverForeground": p.text,
    "quickInputList.hoverIconForeground": p.accentText,
    "quickInput.border": p.border,

    "keybindingLabel.background": p.overlay,
    "keybindingLabel.foreground": p.secondary,
    "keybindingLabel.border": p.border,
    "keybindingLabel.bottomBorder": p.borderStrong,
    "keybindingTable.headerBackground": p.overlay,
    "keybindingTable.rowsBackground": p.overlay,

    "settings.headerForeground": p.text,
    "settings.modifiedItemIndicator": p.accent,
    "settings.dropdownBackground": p.input,
    "settings.dropdownForeground": p.text,
    "settings.dropdownBorder": p.border,
    "settings.dropdownListBorder": p.border,
    "settings.checkboxBackground": p.input,
    "settings.checkboxForeground": p.text,
    "settings.checkboxBorder": p.border,
    "settings.rowHoverBackground": p.overlay,
    "settings.textInputBackground": p.input,
    "settings.textInputForeground": p.text,
    "settings.textInputBorder": p.border,
    "settings.numberInputBackground": p.input,
    "settings.numberInputForeground": p.text,
    "settings.numberInputBorder": p.border,
    "settings.focusedRowBackground": p.overlay,
    "settings.focusedRowBorder": p.borderStrong,
    "settings.headerBorder": p.border,
    "settings.sashBorder": p.border,

    "terminal.background": p.panel,
    "terminal.foreground": p.editorText,
    "terminal.border": p.border,
    "terminal.selectionBackground": p.selectionStrong,
    "terminal.selectionForeground": p.text,
    "terminal.inactiveSelectionBackground": p.selection,
    "terminal.findMatchBackground": p.yellowWash,
    "terminal.findMatchHighlightBackground": `${p.yellowBright}24`,
    "terminal.hoverHighlightBackground": p.overlayStrong,
    "terminalCursor.foreground": p.accentText,
    "terminalCursor.background": p.panel,
    "terminal.tab.activeBorder": p.accent,
    "terminal.dropBackground": p.accentWash,
    "terminalOverviewRuler.cursorForeground": p.accent,
    "terminalOverviewRuler.findMatchForeground": p.yellow,
    "terminalCommandDecoration.defaultBackground": p.muted,
    "terminalCommandDecoration.successBackground": p.green,
    "terminalCommandDecoration.errorBackground": p.red,
    "terminalCommandGuide.foreground": p.borderStrong,
    "terminalStickyScroll.background": p.panel,
    "terminalStickyScrollHover.background": p.chromeSolid,
    "terminalStickyScroll.border": transparent,
    "terminalOverviewRuler.border": transparent,
    "terminal.ansiBlack": p.type === "dark" ? "#1C1C1E" : "#3A3A3C",
    "terminal.ansiRed": p.red,
    "terminal.ansiGreen": p.green,
    "terminal.ansiYellow": p.yellow,
    "terminal.ansiBlue": p.blue,
    "terminal.ansiMagenta": p.purple,
    "terminal.ansiCyan": p.cyan,
    "terminal.ansiWhite": "#D1D1D6",
    "terminal.ansiBrightBlack": p.muted,
    "terminal.ansiBrightRed": p.redBright,
    "terminal.ansiBrightGreen": p.greenBright,
    "terminal.ansiBrightYellow": p.yellowBright,
    "terminal.ansiBrightBlue": p.blueBright,
    "terminal.ansiBrightMagenta": p.purpleBright,
    "terminal.ansiBrightCyan": p.cyanBright,
    "terminal.ansiBrightWhite": p.white,

    "gitDecoration.addedResourceForeground": p.green,
    "gitDecoration.modifiedResourceForeground": p.orange,
    "gitDecoration.deletedResourceForeground": p.red,
    "gitDecoration.renamedResourceForeground": p.cyan,
    "gitDecoration.untrackedResourceForeground": p.green,
    "gitDecoration.ignoredResourceForeground": p.gitIgnored,
    "gitDecoration.conflictingResourceForeground": p.red,
    "gitDecoration.submoduleResourceForeground": p.purple,
    "gitDecoration.stageModifiedResourceForeground": p.orange,
    "gitDecoration.stageDeletedResourceForeground": p.red,
    "scmGraph.historyItemHoverLabelForeground": p.text,
    "scmGraph.foreground1": p.blue,
    "scmGraph.foreground2": p.green,
    "scmGraph.foreground3": p.purple,
    "scmGraph.foreground4": p.orange,
    "scmGraph.foreground5": p.cyan,

    "debugToolBar.background": p.elevated,
    "debugToolBar.border": p.border,
    "debugIcon.startForeground": p.green,
    "debugIcon.pauseForeground": p.blue,
    "debugIcon.stopForeground": p.red,
    "debugIcon.disconnectForeground": p.red,
    "debugIcon.restartForeground": p.green,
    "debugIcon.stepOverForeground": p.blue,
    "debugIcon.stepIntoForeground": p.blue,
    "debugIcon.stepOutForeground": p.blue,
    "debugIcon.continueForeground": p.green,
    "debugIcon.stepBackForeground": p.blue,
    "debugConsole.infoForeground": p.blue,
    "debugConsole.warningForeground": p.orange,
    "debugConsole.errorForeground": p.red,
    "debugConsole.sourceForeground": p.secondary,
    "debugConsoleInputIcon.foreground": p.accentText,
    "debugExceptionWidget.background": p.elevated,
    "debugExceptionWidget.border": p.red,
    "editor.stackFrameHighlightBackground": p.yellowWash,
    "editor.focusedStackFrameHighlightBackground": p.greenWash,

    "testing.iconFailed": p.red,
    "testing.iconErrored": p.red,
    "testing.iconPassed": p.green,
    "testing.runAction": p.green,
    "testing.iconQueued": p.yellow,
    "testing.iconUnset": p.muted,
    "testing.iconSkipped": p.orange,
    "testing.peekBorder": p.accent,
    "testing.peekHeaderBackground": p.chromeSolid,
    "testing.message.error.decorationForeground": p.red,
    "testing.message.error.lineBackground": p.redWash,
    "testing.message.info.decorationForeground": p.blue,
    "testing.message.info.lineBackground": p.blueWash,

    "welcomePage.background": p.canvas,
    "welcomePage.progress.background": p.overlayStrong,
    "welcomePage.progress.foreground": p.accent,
    "welcomePage.tileBackground": p.panel,
    "welcomePage.tileHoverBackground": p.overlayStrong,
    "welcomePage.tileBorder": p.border,
    "walkThrough.embeddedEditorBackground": p.editor,
    "walkthrough.stepTitle.foreground": p.text,

    "notebook.editorBackground": p.editor,
    "notebook.cellBorderColor": p.border,
    "notebook.cellHoverBackground": p.overlay,
    "notebook.cellInsertionIndicator": p.accent,
    "notebook.cellStatusBarItemHoverBackground": p.overlayStrong,
    "notebook.cellToolbarSeparator": p.border,
    "notebook.focusedCellBackground": p.editor,
    "notebook.focusedCellBorder": p.accent,
    "notebook.focusedEditorBorder": p.accent,
    "notebook.inactiveFocusedCellBorder": p.borderStrong,
    "notebook.outputContainerBackgroundColor": p.overlay,
    "notebook.outputContainerBorderColor": p.border,
    "notebook.selectedCellBackground": p.accentWash,
    "notebook.selectedCellBorder": p.accent,
    "notebook.symbolHighlightBackground": p.yellowWash,

    "merge.currentHeaderBackground": p.greenWash,
    "merge.currentContentBackground": `${p.greenBright}14`,
    "merge.incomingHeaderBackground": p.blueWash,
    "merge.incomingContentBackground": `${p.blueBright}14`,
    "merge.commonHeaderBackground": p.overlayStrong,
    "merge.commonContentBackground": p.overlay,
    "merge.border": p.border,
    "mergeEditor.change.background": p.orangeWash,
    "mergeEditor.change.word.background": `${p.orangeBright}3D`,
    "mergeEditor.conflict.unhandledUnfocused.border": p.red,
    "mergeEditor.conflict.unhandledFocused.border": p.redBright,
    "mergeEditor.conflict.handledUnfocused.border": p.green,
    "mergeEditor.conflict.handledFocused.border": p.greenBright,
    "mergeEditor.conflict.handled.minimapOverViewRuler": p.green,
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": p.red,

    "charts.foreground": p.text,
    "charts.lines": p.borderStrong,
    "charts.blue": p.blueBright,
    "charts.red": p.redBright,
    "charts.yellow": p.yellowBright,
    "charts.orange": p.orangeBright,
    "charts.green": p.greenBright,
    "charts.purple": p.purpleBright,
    "gauge.background": p.blueWash,
    "gauge.foreground": p.blue,
    "gauge.border": p.border,
    "gauge.warningBackground": p.yellowWash,
    "gauge.warningForeground": p.yellow,
    "gauge.errorBackground": p.redWash,
    "gauge.errorForeground": p.red,
    "ports.iconRunningProcessForeground": p.green,

    "toolbar.hoverBackground": p.overlayStrong,
    "toolbar.hoverOutline": transparent,
    "toolbar.activeBackground": p.selection,
    "banner.background": p.accentWash,
    "banner.foreground": p.text,
    "banner.iconForeground": p.accentText,

    "inlineChat.background": p.elevated,
    "inlineChat.foreground": p.text,
    "inlineChat.border": p.border,
    "inlineChat.shadow": p.shadow,
    "inlineChatInput.background": p.input,
    "inlineChatInput.border": p.border,
    "inlineChatInput.focusBorder": p.accent,
    "inlineChatInput.placeholderForeground": p.muted,
    "inlineChatDiff.inserted": p.greenWash,
    "inlineChatDiff.removed": p.redWash,
    "chat.requestBubbleBackground": p.accentWash,
    "chat.requestBubbleHoverBackground": p.selection,
    "chat.avatarBackground": p.accentWash,
    "chat.avatarForeground": p.accentText,
    "chat.slashCommandBackground": p.blueWash,
    "chat.slashCommandForeground": p.blue,
    "chat.editedFileForeground": p.orange,
    "chat.linesAddedForeground": p.green,
    "chat.linesRemovedForeground": p.red,
    "chat.inputWorkingBorderColor1": p.accent,
    "chat.inputWorkingBorderColor2": p.blue,
    "chat.inputWorkingBorderColor3": p.accentText,
    "chat.thinkingShimmer": p.muted,
    "editorCommentsWidget.rangeBackground": p.accentWash,
    "editorCommentsWidget.rangeActiveBackground": p.selection,
    "editorCommentsWidget.replyInputBackground": p.input,
    "editorCommentsWidget.resolvedBorder": p.green,
    "editorCommentsWidget.unresolvedBorder": p.accent,
    "agentStatusIndicator.background": p.elevated,
    "agents.background": p.editor,
    "agentsPanel.background": p.panel,
    "agentsPanel.foreground": p.text,
    "agentsPanel.border": p.border,
    "agentsGradient.tintColor": p.accent,
    "agentsChatInput.background": p.elevated,
    "agentsChatInput.foreground": p.text,
    "agentsChatInput.border": p.border,
    "agentsChatInput.focusBorder": p.accent,
    "agentsChatInput.placeholderForeground": p.muted,
    "agentsNewSessionButton.background": transparent,
    "agentsNewSessionButton.foreground": p.text,
    "agentsNewSessionButton.border": p.border,
    "agentsNewSessionButton.hoverBackground": p.overlayStrong,
    "agentsBadge.background": p.primary,
    "agentsBadge.foreground": p.primaryForeground,
    "agentsUnreadBadge.background": p.blue,
    "agentsUnreadBadge.foreground": p.blueForeground
  };
}

function makeTokenColors(p) {
  const dark = p.type === "dark";
  const syntax = dark
    ? {
        comment: "#98989D",
        keyword: "#FF8A8F",
        function: "#D2ABFF",
        type: "#6CD7E8",
        string: "#82D897",
        number: "#FFB272",
        variable: "#EDEDF0",
        property: "#74BCFF",
        operator: "#C7C7CC",
        tag: "#FF9188",
        attribute: "#C6A7FF",
        regexp: "#F0D06F",
        invalid: "#FF6B6F"
      }
    : {
        comment: "#6E6E73",
        keyword: "#A23B4A",
        function: "#6947A0",
        type: "#0A7184",
        string: "#29723B",
        number: "#A25121",
        variable: "#2C2C2E",
        property: "#116AAB",
        operator: "#5A5A5F",
        tag: "#AD493A",
        attribute: "#75569E",
        regexp: "#856000",
        invalid: "#C1252D"
      };

  return [
    {
      name: "Comments",
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: syntax.comment, fontStyle: "italic" }
    },
    {
      name: "Keywords and control flow",
      scope: [
        "keyword",
        "storage.type",
        "storage.modifier",
        "keyword.control",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.logical"
      ],
      settings: { foreground: syntax.keyword }
    },
    {
      name: "Operators and punctuation",
      scope: [
        "keyword.operator",
        "punctuation.separator",
        "punctuation.terminator",
        "punctuation.accessor",
        "meta.brace"
      ],
      settings: { foreground: syntax.operator }
    },
    {
      name: "Functions and methods",
      scope: [
        "entity.name.function",
        "support.function",
        "variable.function",
        "meta.function-call entity.name.function"
      ],
      settings: { foreground: syntax.function }
    },
    {
      name: "Types and classes",
      scope: [
        "entity.name.type",
        "entity.name.class",
        "support.type",
        "support.class",
        "storage.type.class",
        "storage.type.interface"
      ],
      settings: { foreground: syntax.type }
    },
    {
      name: "Strings",
      scope: [
        "string",
        "string.quoted",
        "string.template",
        "punctuation.definition.string"
      ],
      settings: { foreground: syntax.string }
    },
    {
      name: "Numbers, constants, and language values",
      scope: [
        "constant.numeric",
        "constant.language",
        "constant.character",
        "constant.other",
        "variable.language"
      ],
      settings: { foreground: syntax.number }
    },
    {
      name: "Variables and parameters",
      scope: [
        "variable",
        "variable.other",
        "variable.parameter",
        "meta.definition.variable"
      ],
      settings: { foreground: syntax.variable }
    },
    {
      name: "Properties and object keys",
      scope: [
        "variable.other.property",
        "variable.other.object.property",
        "support.type.property-name",
        "meta.object-literal.key",
        "meta.property-name"
      ],
      settings: { foreground: syntax.property }
    },
    {
      name: "Tags",
      scope: [
        "entity.name.tag",
        "punctuation.definition.tag",
        "support.class.component"
      ],
      settings: { foreground: syntax.tag }
    },
    {
      name: "Attributes",
      scope: ["entity.other.attribute-name", "meta.tag.attributes"],
      settings: { foreground: syntax.attribute }
    },
    {
      name: "Regular expressions",
      scope: ["string.regexp", "source.regexp", "constant.character.escape"],
      settings: { foreground: syntax.regexp }
    },
    {
      name: "Escapes",
      scope: ["constant.character.escape", "string.regexp constant.character.escape"],
      settings: { foreground: syntax.type, fontStyle: "bold" }
    },
    {
      name: "Imports and namespaces",
      scope: [
        "entity.name.namespace",
        "entity.name.module",
        "meta.module-reference",
        "support.module"
      ],
      settings: { foreground: syntax.type }
    },
    {
      name: "Decorators and annotations",
      scope: [
        "meta.decorator",
        "entity.name.function.decorator",
        "storage.type.annotation"
      ],
      settings: { foreground: syntax.attribute }
    },
    {
      name: "JSON keys",
      scope: [
        "support.type.property-name.json",
        "string.json support.type.property-name"
      ],
      settings: { foreground: syntax.property }
    },
    {
      name: "CSS selectors",
      scope: [
        "entity.other.attribute-name.class.css",
        "entity.other.attribute-name.id.css",
        "entity.name.tag.css"
      ],
      settings: { foreground: syntax.tag }
    },
    {
      name: "CSS properties",
      scope: ["support.type.property-name.css", "meta.property-name.css"],
      settings: { foreground: syntax.property }
    },
    {
      name: "Markdown headings",
      scope: ["markup.heading", "markup.heading entity.name"],
      settings: { foreground: syntax.function, fontStyle: "bold" }
    },
    {
      name: "Markdown bold",
      scope: ["markup.bold"],
      settings: { foreground: p.text, fontStyle: "bold" }
    },
    {
      name: "Markdown italic",
      scope: ["markup.italic"],
      settings: { foreground: p.text, fontStyle: "italic" }
    },
    {
      name: "Markdown inline code",
      scope: ["markup.inline.raw", "markup.fenced_code.block"],
      settings: { foreground: syntax.string }
    },
    {
      name: "Markdown links",
      scope: ["string.other.link", "constant.other.reference.link"],
      settings: { foreground: syntax.property, fontStyle: "underline" }
    },
    {
      name: "Markdown quotes",
      scope: ["markup.quote"],
      settings: { foreground: syntax.comment, fontStyle: "italic" }
    },
    {
      name: "Diff inserted",
      scope: ["markup.inserted", "punctuation.definition.inserted"],
      settings: { foreground: p.green }
    },
    {
      name: "Diff deleted",
      scope: ["markup.deleted", "punctuation.definition.deleted"],
      settings: { foreground: p.red }
    },
    {
      name: "Diff changed",
      scope: ["markup.changed", "punctuation.definition.changed"],
      settings: { foreground: p.orange }
    },
    {
      name: "Invalid and deprecated",
      scope: ["invalid", "invalid.illegal", "invalid.deprecated"],
      settings: { foreground: syntax.invalid, fontStyle: "italic underline" }
    },
    {
      name: "Diagnostic info",
      scope: ["token.info-token"],
      settings: { foreground: p.blue }
    },
    {
      name: "Diagnostic warning",
      scope: ["token.warn-token"],
      settings: { foreground: p.orange }
    },
    {
      name: "Diagnostic error",
      scope: ["token.error-token"],
      settings: { foreground: p.red }
    },
    {
      name: "Diagnostic debug",
      scope: ["token.debug-token"],
      settings: { foreground: p.purple }
    }
  ];
}

function makeSemanticTokenColors(p) {
  const dark = p.type === "dark";
  return {
    namespace: dark ? "#6CD7E8" : "#0A7184",
    type: dark ? "#6CD7E8" : "#0A7184",
    class: dark ? "#6CD7E8" : "#0A7184",
    enum: dark ? "#6CD7E8" : "#0A7184",
    interface: dark ? "#6CD7E8" : "#0A7184",
    struct: dark ? "#6CD7E8" : "#0A7184",
    typeParameter: dark ? "#69D9F3" : "#00788F",
    parameter: dark ? "#EDEDF0" : "#2C2C2E",
    variable: dark ? "#EDEDF0" : "#2C2C2E",
    property: dark ? "#74BCFF" : "#116AAB",
    enumMember: dark ? "#FFB272" : "#A25121",
    event: dark ? "#F08AB1" : "#A83B68",
    function: dark ? "#D2ABFF" : "#6947A0",
    method: dark ? "#D2ABFF" : "#6947A0",
    macro: dark ? "#FFB272" : "#A25121",
    label: dark ? "#C7C7CC" : "#5A5A5F",
    comment: { foreground: dark ? "#98989D" : "#6E6E73", italic: true },
    string: dark ? "#82D897" : "#29723B",
    number: dark ? "#FFB272" : "#A25121",
    regexp: dark ? "#F0D06F" : "#856000",
    operator: dark ? "#C7C7CC" : "#5A5A5F",
    keyword: dark ? "#FF8A8F" : "#A23B4A",
    decorator: dark ? "#C6A7FF" : "#75569E",
    "*.declaration": { bold: false },
    "variable.readonly": { foreground: dark ? "#FFB272" : "#A25121" },
    "property.readonly": { foreground: dark ? "#6CD7E8" : "#0A7184" },
    "method.declaration": { bold: false },
    "function.declaration": { bold: false },
    "*.deprecated": { strikethrough: true }
  };
}

async function writeTheme(mode, palette) {
  const theme = {
    $schema: "vscode://schemas/color-theme",
    name: palette.name,
    type: palette.type,
    semanticHighlighting: true,
    colors: makeColors(palette),
    tokenColors: makeTokenColors(palette),
    semanticTokenColors: makeSemanticTokenColors(palette)
  };
  const outputPath = resolve(
    projectRoot,
    "themes",
    `golden-gate-${mode}-color-theme.json`
  );
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${JSON.stringify(theme, null, 2)}\n`);
}

await Promise.all(
  Object.entries(palettes).map(([mode, palette]) => writeTheme(mode, palette))
);

console.log("Built Golden Gate light and dark color themes.");
